### ISSUE TITLE
What about `with-remote` or `let-remote`?

### ISSUE THREAD

**Issue by noncom** [sunng87/slacker#36]
It is not always comfortable to get remote procedures declared at the top level. Is it currently possible to somehow get a "binding" for a remote function but not on the global level? The usecase is that such handles can be generated and stored for later use and/or not clutter the namespace.

Currently I am experimenting with creating a distributed program, where a server talks to numerous workers, presenting a web frontend for all of them. It would be useful to store slacker client access for each worker in that workers map and call various functions on demand. Since workers are identical and have identical function names, it is impossible to define them on the top level without making a big mess.

Looking at Slacker code I see this is possible by decoupling the `fn` creating from the `def-remote` macro. For now I have just created `remote` macro for me that will simply return the `fn` which I can assign inside a `let` binding.

**Comment by sunng87** [comment]
Thanks for using slacker. If I understand correctly, you can use `slacker.client/with-slacker` macro. It allows you to assign a different slacker client when calling remote function:

```
(def sc1 (slackerc ...))
(def sc2 (slackerc ...))

(defn-remote sc1 some-function)

;; this will call some-function with sc1 
(some-function)

;; To call it with sc2,
(with-slackerc sc2
  (some-function))
```

**Comment by noncom** [comment]
Hmm, really, this can get close to what I describe but here are some things that are not quite fit:

* I have to have some `slackerc` to make my first `defn-remote`, and at the start, the server has no workers connected, so it has no `slackerc` to create the definition upon. The clients can come and go, so I would not want to get attached to them. Also it seems a little strange to have some `slackerc` just to create the defns and then rebind them for other clients.

* I cannot store such defns in a `{}` to call them later, probably from a different place.

* Decoupling is good all in all.

So, for now I will go with my `remote` macro which allows to decouple from particular `slackerc` instances. I have not yet put this design in use, since I am now at the initial building stage, but it is half way through already, so I hope, it will all work fine!

Other than this minor inconvenience, Slacker seems to be a very miraculous library! :)

**Comment by sunng87** [comment]
hmm... 

Actually the `slackerc` required in `defn-remote` is just a default one. You can always use a different one to call the remote function, by `with-slackerc`.

Have you checked  [slacker-cluster](https://github.com/sunng87/slacker-cluster)? It uses a zookeeper to track available servers, and your client won't need to maintain a full list of servers, just call the function. Also you can define a grouping function to customize server(s) will be invoked.

**Comment by noncom** [comment]
Yeah, but there is no default `slackerc` for a master server when no workers have yet connected. If the server starts and waits for workers, there are no clients to create the remote upon. It is waiting for a worker to connect and identify itself, and after that it will register it for RPC calls. Also, all clients can be lost if the worker nodes go offline or something, so the assumption that there is some default `slackerc` does not hold.

I have taken a look at slacker-cluster. Probably it will suit more for my needs, if every function along with its normal arguments will receive a worker ID and the `:grouping` function will return the worker appropriate for that ID. It is not clear from the readme, however what is the type of `servers` passed to the grouping function (it would be good to add its description to the readme btw), but I assume it is some sort of a collection of `"ip:port"` elements and I can pick an appropriate one, designated by the worker ID passed to the function call mentioned at the beginning of this paragraph.

I will first finish my current design, then l will create a drop-in replacement for my server solution based on slacker-cluster instead of slacker as I have mentioned above and hopefully get it working. Due to the bidirectional nature of this topology I will use both slacker and slacker-cluster:

* server->workers connection is one-to-many, it will use slacker-cluster
* worker->server connection is one-to-one and it will use slacker.

The anticipated ability of slacker-cluster to consciously differentiate between the servers maybe just what I need, however it comes at the cost of introducing an additional mysterious entity "zookeeper".. As per my thinking I will have two interchangable solutions, one based on modified slacker and another one based on slacker-cluster, I will be able to compare how they work and chose the better one.

Eh, sorry if this all sounds convoluted or vague, I am simply trying to organize a server with volatile workers, with a bidirectional RPC/data connection between them. A similar design can be seen in multiplayer client-server games or TeamCity CI. I just thought that RPC is more comfortable than plain TCP for that.

I think that there is not much else to say about then until I get it working.

**Comment by sunng87** [comment]
I'm OK to improve the `defn-remote` and make it independent to a default `slackerc`. 

Thanks. And also feel free to contact me if you see any issue of slacker/slacker-cluster during your development.
